default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: admin
  password: 1107
  pool: 5

development:
  <<: *default
  database: challenge_development

test:
  <<: *default
  database: challenge_dev_test

production:
  <<: *default
  database: challenge_production
