default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  pool: 5

development:
  <<: *default
  database: challenge_development

test:
  <<: *default
  database: challenge_dev_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>